services:
  postgres:
    image: postgres:17.6-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - novafi-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:8.2.1-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']

  # nest:
  #   container_name: novafi
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}

volumes:
  novafi-db:
